name: Secure Deploy to ENS + IPFS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full git history for commit info

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install Storacha CLI
        run: npm install -g @storacha/client

      - name: Setup Storacha credentials
        run: |
          mkdir -p ~/.storacha
          echo "${{ secrets.STORACHA_TOKEN }}" > ~/.storacha/token
        if: env.STORACHA_TOKEN != ''

      - name: Install secure-deploy CLI
        run: |
          cd path/to/secure-deploy
          npm install
          npm run build
          npm link

      - name: Deploy to ENS + IPFS
        run: |
          secure-deploy deploy dist \
            --network sepolia \
            --ens-domain rome.eth \
            --rpc-url ${{ secrets.SEPOLIA_RPC_URL }} \
            --safe-address ${{ secrets.SAFE_ADDRESS }} \
            --safe-threshold 2 \
            --owner-address ${{ secrets.SEPOLIA_OWNER_ADDRESS }} \
            --owner-pk ${{ secrets.SEPOLIA_OWNER_PK }}
        env:
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
          SAFE_ADDRESS: ${{ secrets.SAFE_ADDRESS }}
          SEPOLIA_OWNER_ADDRESS: ${{ secrets.SEPOLIA_OWNER_ADDRESS }}
          SEPOLIA_OWNER_PK: ${{ secrets.SEPOLIA_OWNER_PK }}

      - name: Comment on commit with deployment info
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.sha
            const shortSha = sha.substring(0, 7)

            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha,
              body: `🚀 **Deployment Initiated**\n\n` +
                    `Commit: ${shortSha}\n` +
                    `Safe Transaction created for approval.\n\n` +
                    `View pending transactions: https://app.safe.global/sepolia.safe/${{ secrets.SAFE_ADDRESS }}/transactions/queue`
            })
